const { JsonSchema, Schema } = require("@hyperjump/json-schema-core");
const keywords = require("../keywords");
const metaSchema = require("./meta/schema.schema.json");
const metaHyperSchema = require("./meta/hyper-schema.schema.json");


// JSON Schema Draft-04
Schema.setConfig("http://json-schema.org/draft-04/schema", "jsonReference", true);
Schema.setConfig("http://json-schema.org/draft-04/schema", "idToken", "id");
Schema.setConfig("http://json-schema.org/draft-04/schema", "anchorToken", "id");

Schema.add(metaSchema);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#validate", keywords.validate);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#additionalItems", keywords.additionalItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#additionalProperties", keywords.additionalProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#allOf", keywords.allOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#anyOf", keywords.anyOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#default", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#definitions", keywords.definitions);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#dependencies", keywords.dependencies);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#description", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#enum", keywords.enum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#format", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#items", keywords.items);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#maxItems", keywords.maxItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#maxLength", keywords.maxLength);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#maxProperties", keywords.maxProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#maximum", keywords.maximumExclusiveMaximum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#minItems", keywords.minItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#minLength", keywords.minLength);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#minProperties", keywords.minProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#minimum", keywords.minimumExclusiveMinimum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#multipleOf", keywords.multipleOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#not", keywords.not);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#oneOf", keywords.oneOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#pattern", keywords.pattern);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#patternProperties", keywords.patternProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#properties", keywords.properties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#required", keywords.required);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#title", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#type", keywords.type);
JsonSchema.addKeyword("http://json-schema.org/draft-04/schema#uniqueItems", keywords.uniqueItems);

// JSON Hyper-Schema Draft-04
Schema.setConfig("http://json-schema.org/draft-04/hyper-schema", "jsonReference", true);
Schema.setConfig("http://json-schema.org/draft-04/hyper-schema", "idToken", "id");
Schema.setConfig("http://json-schema.org/draft-04/hyper-schema", "anchorToken", "id");

Schema.add(metaHyperSchema);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#validate", keywords.validate);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#additionalItems", keywords.additionalItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#additionalProperties", keywords.additionalProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#allOf", keywords.allOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#anyOf", keywords.anyOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#default", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#definitions", keywords.definitions);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#dependencies", keywords.dependencies);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#description", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#enum", keywords.enum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#format", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#fragmentResolution", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#items", keywords.items);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#maxItems", keywords.maxItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#minProperties", keywords.minProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#maxProperties", keywords.maxProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#maximum", keywords.maximumExclusiveMaximum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#media", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#minItems", keywords.minItems);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#minLength", keywords.minLength);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#maxLength", keywords.maxLength);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#minimum", keywords.minimumExclusiveMinimum);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#multipleOf", keywords.multipleOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#links", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#not", keywords.not);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#oneOf", keywords.oneOf);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#pathStart", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#pattern", keywords.pattern);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#patternProperties", keywords.patternProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#properties", keywords.properties);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#readOnly", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#required", keywords.required);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#title", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#type", keywords.type);
JsonSchema.addKeyword("http://json-schema.org/draft-04/hyper-schema#uniqueItems", keywords.uniqueItems);
