const { Keywords } = require("@hyperjump/json-schema-core");


module.exports = {
  additionalItems: require("./additionalItems"),
  additionalItems6: require("./additionalItems6"),
  additionalProperties: require("./additionalProperties"),
  additionalProperties6: require("./additionalProperties6"),
  allOf: require("./allOf"),
  anyOf: require("./anyOf"),
  const: require("./const"),
  contains: require("./contains"),
  containsMinContainsMaxContains: require("./contains-minContains-maxContains"),
  definitions: require("./definitions"),
  dependencies: require("./dependencies"),
  dependentRequired: require("./dependentRequired"),
  dependentSchemas: require("./dependentSchemas"),
  enum: require("./enum"),
  exclusiveMaximum: require("./exclusiveMaximum"),
  exclusiveMinimum: require("./exclusiveMinimum"),
  exclusiveMaximumOas31: require("./exclusiveMaximum-oas31"),
  exclusiveMinimumOas31: require("./exclusiveMinimum-oas31"),
  ifThenElse: require("./if-then-else"),
  items: require("./items"),
  maxItems: require("./maxItems"),
  maxLength: require("./maxLength"),
  maxLength6: require("./maxLength6"),
  maxProperties: require("./maxProperties"),
  maximumExclusiveMaximum: require("./maximum-exclusiveMaximum.js"),
  maximumExclusiveMaximumOas31: require("./maximum-exclusiveMaximum-oas31"),
  maximum: require("./maximum"),
  metaData: Keywords.metaData,
  minItems: require("./minItems"),
  minLength: require("./minLength"),
  minLength6: require("./minLength6"),
  minProperties: require("./minProperties"),
  minimumExclusiveMinimum: require("./minimum-exclusiveMinimum"),
  minimumExclusiveMinimumOas31: require("./minimum-exclusiveMinimum-oas31"),
  minimum: require("./minimum"),
  multipleOf: require("./multipleOf"),
  not: require("./not"),
  oneOf: require("./oneOf"),
  pattern: require("./pattern"),
  patternProperties: require("./patternProperties"),
  properties: require("./properties"),
  propertyNames: require("./propertyNames"),
  $recursiveRef: require("./recursiveRef"),
  $ref: require("./ref"),
  required: require("./required"),
  type: require("./type"),
  unevaluatedItems: require("./unevaluatedItems"),
  unevaluatedProperties: require("./unevaluatedProperties"),
  uniqueItems: require("./uniqueItems"),
  validate: Keywords.validate
};
