import type { Json } from "@hyperjump/json-pointer";
import type { Core } from "./core";
import type { Configuration } from "./configuration";
import type { Instance } from "./instance";
import type { InvalidSchemaError as _InvalidSchemaError } from "./invalid-schema-error";
import type { Keywords, Keyword } from "./keywords";
import type { Schema } from "./schema";
import type { MediaTypes } from "./media-types";


export type JsonSchemaValidator = {
  addSchema: Schema["add"];
  validate: Core["validate"];
  compile: Core["compile"];
  interpret: Core["interpret"];
  setMetaOutputFormat: Configuration["setMetaOutputFormat"];
  getMetaOutputFormat: Configuration["getMetaOutputFormat"];
  setShouldMetaValidate: Configuration["setShouldMetaValidate"];
  getShouldMetaValidate: Configuration["getShouldMetaValidate"];
  setUnstableKeywordEnabled: Configuration["setUnstableKeywordEnabled"];
  isUnstableKeywordEnabled: Configuration["isUnstableKeywordEnabled"];
  addMediaTypePlugin: MediaTypes["addMediaTypePlugin"];
  FLAG: Core["FLAG"];
  BASIC: Core["BASIC"];
  DETAILED: Core["DETAILED"];
  VERBOSE: Core["VERBOSE"];
  InvalidSchemaError: _InvalidSchemaError;
  Keywords: Keywords;
  Schema: Schema;
  Instance: Instance;
  Validate: Keyword;
};

export const addSchema: JsonSchemaValidator["addSchema"];
export const validate: JsonSchemaValidator["validate"];
export const compile: JsonSchemaValidator["compile"];
export const interpret: JsonSchemaValidator["interpret"];
export const setMetaOutputFormat: JsonSchemaValidator["setMetaOutputFormat"];
export const getMetaOutputFormat: JsonSchemaValidator["getMetaOutputFormat"];
export const setShouldMetaValidate: JsonSchemaValidator["setShouldMetaValidate"];
export const getShouldMetaValidate: JsonSchemaValidator["getShouldMetaValidate"];
export const setUnstableKeywordEnabled: JsonSchemaValidator["setUnstableKeywordEnabled"];
export const isUnstableKeywordEnabled: JsonSchemaValidator["isUnstableKeywordEnabled"];
export const addMediaTypePlugin: JsonSchemaValidator["addMediaTypePlugin"];
export const FLAG: JsonSchemaValidator["FLAG"];
export const BASIC: JsonSchemaValidator["BASIC"];
export const DETAILED: JsonSchemaValidator["DETAILED"];
export const VERBOSE: JsonSchemaValidator["VERBOSE"];
export const InvalidSchemaError: JsonSchemaValidator["InvalidSchemaError"];
export const Keywords: JsonSchemaValidator["Keywords"];
export const Schema: JsonSchemaValidator["Schema"];
export const Instance: JsonSchemaValidator["Instance"];
export const Validate: JsonSchemaValidator["Validate"];

export type JsonSchema = boolean | {
  $schema?: "https://json-schema.org/validation";
  $id?: string;
  $anchor?: string;
  $ref?: string;
  $dynamicRef?: string;
  $dynamicAnchor?: string;
  $vocabulary?: Record<string, boolean>;
  $comment?: string;
  $defs?: Record<string, JsonSchema>;
  additionalItems?: JsonSchema;
  unevaluatedItems?: JsonSchema;
  prefixItems?: JsonSchema[];
  items?: JsonSchema;
  contains?: JsonSchema;
  additionalProperties?: JsonSchema;
  unevaluatedProperties?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  patternProperties?: Record<string, JsonSchema>;
  dependentSchemas?: Record<string, JsonSchema>;
  propertyNames?: JsonSchema;
  if?: JsonSchema;
  then?: JsonSchema;
  else?: JsonSchema;
  allOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  not?: JsonSchema;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: number;
  minimum?: number;
  exclusiveMinimum?: number;
  maxLength?: number;
  minLength?: number;
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  uniqueItems?: boolean;
  maxContains?: number;
  minContains?: number;
  maxProperties?: number;
  minProperties?: number;
  required?: string[];
  dependentRequired?: Record<string, string[]>;
  const?: Json;
  enum?: Json[];
  type?: JsonSchemaType | JsonSchemaType[];
  title?: string;
  description?: string;
  default?: Json;
  deprecated?: boolean;
  readOnly?: boolean;
  writeOnly?: boolean;
  examples?: Json[];
  format?: "date-time" | "date" | "time" | "duration" | "email" | "idn-email" | "hostname" | "idn-hostname" | "ipv4" | "ipv6" | "uri" | "uri-reference" | "iri" | "iri-reference" | "uuid" | "uri-template" | "json-pointer" | "relative-json-pointer" | "regex";
  contentMediaType?: string;
  contentEncoding?: string;
  contentSchema?: JsonSchema;
};

export type JsonSchemaType = "object" | "array" | "string" | "number" | "integer" | "boolean" | "null";

export * from "./core";
export * from "./keywords";
export * from "./schema";
export * from "./instance";
export * from "./media-types";

declare const jsonSchema: JsonSchemaValidator;
export default jsonSchema;
