const Core = require("./core");
const Schema = require("./schema");

const draft201909MetaSchema = require("./meta/draft-2019-09/schema.json");
const draft201909CoreMetaSchema = require("./meta/draft-2019-09/meta/core.json");
const draft201909ApplicatorMetaSchema = require("./meta/draft-2019-09/meta/applicator.json");
const draft201909ValidationMetaSchema = require("./meta/draft-2019-09/meta/validation.json");
const draft201909MetaDataMetaSchema = require("./meta/draft-2019-09/meta/meta-data.json");
const draft201909FormatMetaSchema = require("./meta/draft-2019-09/meta/format.json");
const draft201909ContentMetaSchema = require("./meta/draft-2019-09/meta/content.json");

const additionalItems = require("./keywords/additionalItems");
const additionalProperties = require("./keywords/additionalProperties");
const allOf = require("./keywords/allOf");
const anyOf = require("./keywords/anyOf");
const const_ = require("./keywords/const");
const contains = require("./keywords/contains");
const defs = require("./keywords/defs");
const dependentRequired = require("./keywords/dependentRequired");
const dependentSchemas = require("./keywords/dependentSchemas");
const enum_ = require("./keywords/enum");
const exclusiveMaximum = require("./keywords/exclusiveMaximum");
const exclusiveMinimum = require("./keywords/exclusiveMinimum");
const ifThenElse = require("./keywords/if-then-else");
const items = require("./keywords/items");
const maxItems = require("./keywords/maxItems");
const maxLength = require("./keywords/maxLength");
const maxProperties = require("./keywords/maxProperties");
const maximum = require("./keywords/maximum");
const metaData = require("./keywords/meta-data");
const minItems = require("./keywords/minItems");
const minLength = require("./keywords/minLength");
const minProperties = require("./keywords/minProperties");
const minimum = require("./keywords/minimum");
const multipleOf = require("./keywords/multipleOf");
const not = require("./keywords/not");
const oneOf = require("./keywords/oneOf");
const pattern = require("./keywords/pattern");
const patternProperties = require("./keywords/patternProperties");
const properties = require("./keywords/properties");
const propertyNames = require("./keywords/propertyNames");
const recuriveRef = require("./keywords/recursiveRef");
const ref = require("./keywords/ref");
const required = require("./keywords/required");
const type = require("./keywords/type");
const uniqueItems = require("./keywords/uniqueItems");
const validate = require("./keywords/validate");


// JSON Schema Draft-2019-09
Schema.add(draft201909MetaSchema);
Schema.add(draft201909CoreMetaSchema);
Schema.add(draft201909ApplicatorMetaSchema);
Schema.add(draft201909ValidationMetaSchema);
Schema.add(draft201909MetaDataMetaSchema);
Schema.add(draft201909FormatMetaSchema);
Schema.add(draft201909ContentMetaSchema);

Core.addKeyword("https://json-schema.org/draft/2019-09/schema", validate);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#additionalItems", additionalItems);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#additionalProperties", additionalProperties);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#allOf", allOf);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#anyOf", anyOf);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#$comment", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#const", const_);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#contains", contains);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#contentEncoding", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#contentMediaType", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#contentSchema", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#$defs", defs);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#default", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#dependentRequired", dependentRequired);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#dependentSchemas", dependentSchemas);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#deprecated", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#description", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#enum", enum_);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#examples", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#exclusiveMaximum", exclusiveMaximum);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#exclusiveMinimum", exclusiveMinimum);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#if", ifThenElse);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#items", items);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#maxItems", maxItems);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#maxLength", maxLength);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#maxProperties", maxProperties);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#maximum", maximum);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#minItems", minItems);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#minLength", minLength);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#minProperties", minProperties);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#minimum", minimum);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#multipleOf", multipleOf);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#not", not);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#oneOf", oneOf);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#pattern", pattern);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#patternProperties", patternProperties);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#properties", properties);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#propertyNames", propertyNames);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#$recursiveRef", recuriveRef);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#$ref", ref);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#readOnly", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#required", required);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#title", metaData);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#type", type);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#uniqueItems", uniqueItems);
Core.addKeyword("https://json-schema.org/draft/2019-09/schema#writeOnly", metaData);

module.exports = { ...Schema, ...Core };
