const { JsonSchema, Schema } = require("@hyperjump/json-schema-core");
const keywords = require("../keywords");
const metaSchema = require("./meta/schema.schema.json");


Schema.setConfig("http://json-schema.org/draft-06/schema", "jsonReference", true);
Schema.setConfig("http://json-schema.org/draft-06/schema", "idToken", "$id");
Schema.setConfig("http://json-schema.org/draft-06/schema", "anchorToken", "$id");

Schema.add(metaSchema);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#validate", keywords.validate);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#additionalItems", keywords.additionalItems6);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#additionalProperties", keywords.additionalProperties6);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#allOf", keywords.allOf);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#anyOf", keywords.anyOf);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#const", keywords.const);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#contains", keywords.contains);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#default", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#definitions", keywords.definitions);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#dependencies", keywords.dependencies);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#description", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#enum", keywords.enum);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#examples", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#exclusiveMaximum", keywords.exclusiveMaximum);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#exclusiveMinimum", keywords.exclusiveMinimum);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#format", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#items", keywords.items);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#maxItems", keywords.maxItems);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#maxLength", keywords.maxLength6);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#maxProperties", keywords.maxProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#maximum", keywords.maximum);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#minItems", keywords.minItems);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#minLength", keywords.minLength6);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#minProperties", keywords.minProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#minimum", keywords.minimum);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#multipleOf", keywords.multipleOf);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#not", keywords.not);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#oneOf", keywords.oneOf);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#pattern", keywords.pattern);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#patternProperties", keywords.patternProperties);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#properties", keywords.properties);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#propertyNames", keywords.propertyNames);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#required", keywords.required);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#title", keywords.metaData);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#type", keywords.type);
JsonSchema.addKeyword("http://json-schema.org/draft-06/schema#uniqueItems", keywords.uniqueItems);
